---
- name: determine the deploy location
  set_fact:
    destination: "{{ tomcat_directory }}/{{ item.name }}/{{ tomcat_archive[tomcat_names.version | default (tomcat_version)]['dir'] }}/webapps"
    tomcat_wars: "{{item.wars}}"
  with_items:
    - "{{ tomcat_names }}"

- name: "Ensure webapp dir exists"
  file:
    name: "{{ destination }}"
    recurse: true
    state: "directory"
  with_items:
    - "{{ tomcat_names }}"

- name: "loop over tomcat_wars in urls"
  get_url:
    dest: "{{ destination }}/"
    url: "{{ item }}"
    validate_certs: "{{ tomcat_validate_certs }}"
  with_items:
    - "{{ tomcat_wars.url }}"
  when:
    - "tomcat_wars.url is defined"

- name: "loop over tomcat_wars in s3"
  aws_s3:
    bucket: "{{ item.bucket }}"
    dest: "{{ destination }}/{{ item.object | basename }}"
    mode: get
    object: "{{ item.object }}"
    region: "{{ item.region | default(tomcat_s3_default_region) }}"
    validate_certs: "{{ tomcat_validate_certs }}"
  with_items:
    - "{{ tomcat_wars.s3 }}"
  when:
    - "tomcat_wars.s3 is defined"
